version: '3.8'

services:
  # MongoDB сервис (опционально, если нужна MongoDB)
  # mongodb:
  #   image: mongo:7.0
  #   container_name: whatsapp-mongodb
  #   ports:
  #     - "27017:27017"
  #   command: mongod --replSet rs0
  #   volumes:
  #     - mongodb_data:/data/db
  #   restart: unless-stopped
  #   networks:
  #     - whatsapp-network

  # Основной WhatsApp API сервис
  whatsapp-api:
    build: .
    container_name: whatsapp-api
    ports:
      - "14860:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - DATABASE_PROVIDER=mongodb
      - DATABASE_URL=mongodb+srv://gosuvendor:1q83M8ZuSjskqmkc@cluster1.2juvo.mongodb.net/whatsapp-api?retryWrites=true&w=majority
      - JWT_SECRET=342fc53aba22686c095ddebbbfddd04f
      - JWT_EXPIRATION=24h
      - CORS_ORIGIN=*
      - ADMIN_EMAIL=support@metalogic.kz
      - ADMIN_PASSWORD=rwEdArEXbaoazHap
      - ADMIN_FIRST_NAME=Admin
      - ADMIN_LAST_NAME=User
      - ENABLE_CRON_JOBS=true
      - CRON_SCHEDULE=0 */6 * * *
    volumes:
      - whatsapp_sessions:/usr/src/app/instances
      - ./uploads:/usr/src/app/uploads
      - ./logs:/usr/src/app/logs
      - ./data:/usr/src/app/data
    depends_on:
      - mongodb
    networks:
      - whatsapp-network
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    restart: unless-stopped

  # Nginx reverse proxy (опционально)
  # nginx:
  #   image: nginx:alpine
  #   container_name: whatsapp-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - whatsapp-api
  #   restart: unless-stopped
  #   networks:
  #     - whatsapp-network
  #   profiles:
  #     - with-nginx

volumes:
  mongodb_data:
    driver: local
  whatsapp_instances:
    driver: local
  whatsapp_uploads:
    driver: local
  whatsapp_logs:
    driver: local
  whatsapp_data:
    driver: local
  whatsapp_sessions:
    driver: local

networks:
  whatsapp-network:
    driver: bridge
